services:
  comfyui:
    image: ghcr.io/ai-dock/comfyui:latest-cuda
    container_name: comfyui
    restart: unless-stopped
    ipc: host
    shm_size: "16gb"

    ports:
      - "8188:8188"
      
    environment:
      - COMFYUI_PORT_HOST=8188
      - AUTO_UPDATE=true
      - PYTHONWARNINGS=ignore
      - SUPERVISOR_NO_AUTOSTART=cloudflared,quicktunnel
      - WEB_ENABLE_AUTH=false
      - CM_BYPASS_SECURITY_CHECK=1
      - PYTHONPATH=/opt/ComfyUI
      - ARGS=--normalvram --use-xformers --fp16-vae
      - PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.8,max_split_size_mb:64
      - COMFYUI_MANAGER_PYTHON_EXE=/opt/environments/python/comfyui/bin/python      
      # Explicitly declare runtime visibility inside the wrapper
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=all

    volumes:
      - comfyui-venv-storage:/opt/environments/python/comfyui
      - ./provisioning.sh:/opt/ai-dock/bin/provisioning.sh
      - /home/nui/dev/ComfyUI:/opt/ComfyUI

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu, compute, utility, video]

volumes:
  comfyui-venv-storage:
